### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by ronytesler** [dfleury2/beauty#14]
after running `cmake --build . -j4` I get:
`fatal error: boost/json.hpp: No such file or directory #include <boost/json.hpp>

**Comment by dfleury2** [comment]
Hi,
which version of boost are you using ?
Beauty is now using the Boost.json library available in Boost 1.74 or earlier.

**Comment by ronytesler** [comment]
1.71.0.0ubunbu2

**Comment by dfleury2** [comment]
Not a good one.

If you can not update to newer version, you can remove the json usage in the code directly (related to Swagger)

**Comment by ronytesler** [comment]
Why? It's earlier than 1.75.

**Comment by dfleury2** [comment]
Sorry, my bad english, I probably mean "later", or 1.74+ (1.75, 76, ... 1.81)

**Comment by ronytesler** [comment]
It says I have the newest version (1.71.0.0ubuntu2) after running apt-get update and apt-get install libboost-all-dev

**Comment by ronytesler** [comment]
I downloaded and installed version 1.81 of boost. Now I get this error when I run `cmake --build . -j4`:
`'class boost::core::basic_string_view<char>'} has no member named 'to_string'
src/CMakeFiles/beauty.div/build.make:154: src/CMakeFiles/beauty.dir/server.cpp.o

**Comment by ronytesler** [comment]
I installed version 1.79 and it worked

**Comment by dfleury2** [comment]
I have fix the issue with boost 1.81.
Now, it may compile fine using boost 1.78+
