### ISSUE TITLE
Boost 1.87(latest) support

### ISSUE THREAD

**Issue by barbacar** [dfleury2/beauty#43]
Hello,

Beauty/1.0.4 does not compile with the latest version of Boost.

Could you please release a version that works with the latest version of Boost?

Thank you.

`/tmp/p/b/beaut60439cefb0f3e/b/src/include/beauty/websocket_client.hpp:74:35: error: cannot convert ‘boost::asio::ip::basic_resolver_iterator<boost::asio::ip::tcp>’ to ‘boost::asio::ip::basic_resolver_results<boost::asio::ip::tcp>::endpoint_type’ {aka ‘boost::asio::ip::basic_endpoint<boost::asio::ip::tcp>’}
   74 |                     me->on_connect(ec, ep);
      |                     ~~~~~~~~~~~~~~^~~~~~~~
/tmp/p/b/beaut60439cefb0f3e/b/src/include/beauty/websocket_client.hpp:78:96: note:   initializing argument 2 of ‘void beauty::websocket_client::on_connect(boost::beast::error_code, boost::asio::ip::basic_resolver_results<boost::asio::ip::tcp>::endpoint_type)’
   78 |     void on_connect(beast::error_code ec, asio::ip::tcp::resolver::results_type::endpoint_type ep) {
      |                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
In file included from /tmp/p/b/beaut60439cefb0f3e/b/src/src/client.cpp:8:
/tmp/p/b/beaut60439cefb0f3e/b/src/src/session_client.hpp: In member function ‘void beauty::session_client<SSL>::on_resolve(const boost::system::error_code&, const results_type&)’:
/tmp/p/b/beaut60439cefb0f3e/b/src/src/session_client.hpp:223:56: error: ‘iterator’ in ‘boost::asio::ip::tcp::resolver’ {aka ‘class boost::asio::ip::basic_resolver<boost::asio::ip::tcp>’} does not name a type
  223 |                         const asio::ip::tcp::resolver::iterator& it) {
      |                                                        ^~~~~~~~
/tmp/p/b/beaut60439cefb0f3e/b/src/src/session_client.hpp: In lambda function:
/tmp/p/b/beaut60439cefb0f3e/b/src/src/session_client.hpp:226:14: error: expected ‘{’ before ‘;’ token
  226 |             );
      |              ^
/tmp/p/b/beaut60439cefb0f3e/b/src/src/session_client.hpp: In member function ‘void beauty::session_client<SSL>::on_resolve(const boost::system::error_code&, const results_type&)’:
/tmp/p/b/beaut60439cefb0f3e/b/src/src/session_client.hpp:226:14: error: expected ‘)’ before ‘;’ token
/tmp/p/b/beaut60439cefb0f3e/b/src/src/session_client.hpp:218:32: note: to match this ‘(’
  218 |             asio::async_connect(
      |                                ^
/tmp/p/b/beaut60439cefb0f3e/b/src/src/session_client.hpp:236:56: error: ‘iterator’ in ‘boost::asio::ip::tcp::resolver’ {aka ‘class boost::asio::ip::basic_resolver<boost::asio::ip::tcp>’} does not name a type
  236 |                         const asio::ip::tcp::resolver::iterator& it) {
      |                                                        ^~~~~~~~
/tmp/p/b/beaut60439cefb0f3e/b/src/src/session_client.hpp: In lambda function:
/tmp/p/b/beaut60439cefb0f3e/b/src/src/session_client.hpp:239:14: error: expected ‘{’ before ‘;’ token
  239 |             );
      |              ^
/tmp/p/b/beaut60439cefb0f3e/b/src/src/session_client.hpp: In member function ‘void beauty::session_client<SSL>::on_resolve(const boost::system::error_code&, const results_type&)’:
/tmp/p/b/beaut60439cefb0f3e/b/src/src/session_client.hpp:239:14: error: expected ‘)’ before ‘;’ token
/tmp/p/b/beaut60439cefb0f3e/b/src/src/session_client.hpp:231:32: note: to match this ‘(’
  231 |             asio::async_connect(
      |                                ^
[13/14] Building CXX object src/CMakeFiles/beauty.dir/acceptor.cpp.o
`

**Comment by dfleury2** [comment]
Hi,

can you try the latest commit ?

Should work on boost 1.87.0. I can not test it yet since boost 1.87.0 not available on conancenter.

**Comment by barbacar** [comment]
Hello,

 Thank you for your quick response and improvement.


https://conan.io/center/recipes/boost
I see boost 1.87 available on conan repository.
Can you also please check?
And for testing, yes i want to help if i can.

Thank you.

**Comment by dfleury2** [comment]
Hi,

It did not work for boost 1.87.0, they changed something again. I need to investigate.

Regards,

**Comment by dfleury2** [comment]
It should be ok now. Can you give a try ?

**Comment by barbacar** [comment]
Sorry for the late reply, I had some work to do. It compiles and works fine. A new version may be released. I will open a ticket to add the new package to the conan side once it is ready.

Thanks.

**Comment by dfleury2** [comment]
Done,
1.0.5 and 1.0.6 for Boost 1.86 and 1.87
