### ISSUE TITLE
Migrate to Conan 2.0.

### ISSUE THREAD

**Issue by Ghibranalj** [dfleury2/beauty#22]
I tried building this project with conan v2.04 and it seems to be broken. After some digging around turns out your current conanfile.py is not compatible with conan 2.0.
source : https://docs.conan.io/1/migrating_to_2.0/recipes.html.

The fix is simple.
But it seems like libssl doesn't support conan 2.0 either so compiling with libssl doesn't work.

here's the error from conan 2.04
```bash
ImportError: cannot import name 'ConanFile' from 'conans' (/home/gibi/.local/lib/python3.10/site-packages/conans/__init__.py)
```

Here is the fix according the above mentioned link
```diff
- from conans import ConanFile
+ from conan import ConanFile

- def requirements(self): 
+ def build_requirements(self):
```

Cheers 🍺

**Comment by dfleury2** [comment]
Done. Should work with conan 2.0 now.
